### ISSUE TITLE
_get_unix_timezone incorrect timezone parsing on Amazon Linux AMI release 2018.03

### ISSUE THREAD

**Issue by Dmitrii-I** [sdispater/pendulum#202]
The following happens on Amazon Linux AMI release 2018.03 with pendulum 2.0.0 (but also with 1.5.1):

    Python 3.4.8 (default, Apr 25 2018, 23:50:36)
    [GCC 4.8.5 20150623 (Red Hat 4.8.5-11)] on linux
    Type "help", "copyright", "credits" or "license" for more information.
    >>> from pendulum.tz.local_timezone import _get_unix_timezone
    >>> _get_unix_timezone()
    Traceback (most recent call last):
      File "/home/dmitrii/.local/lib/python3.4/site-packages/pendulum/tz/zoneinfo/reader.py", line 49, in read_for
        file_path = pytzdata.tz_path(timezone)
      File "/usr/local/lib/python3.4/site-packages/pytzdata/__init__.py", line 74, in tz_path
        raise TimezoneNotFound('Timezone {} not found at {}'.format(name, filepath))
    pytzdata.exceptions.TimezoneNotFound: Timezone /usr/share/zoneinfo/Europe/Zurich not found at /usr/local/lib/python3.4/site-packages/pytzdata/zoneinfo/usr/share/zoneinfo/Europe/Zurich

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/home/dmitrii/.local/lib/python3.4/site-packages/pendulum/tz/local_timezone.py", line 206, in _get_unix_timezone
        return Timezone(etctz.replace(' ', '_'))
      File "/home/dmitrii/.local/lib/python3.4/site-packages/pendulum/tz/timezone.py", line 30, in __init__
        tz = read(name, extend=extended)
      File "/home/dmitrii/.local/lib/python3.4/site-packages/pendulum/tz/zoneinfo/__init__.py", line 9, in read
        return Reader(extend=extend).read_for(name)
      File "/home/dmitrii/.local/lib/python3.4/site-packages/pendulum/tz/zoneinfo/reader.py", line 51, in read_for
        raise InvalidTimezone(timezone)
    pendulum.tz.zoneinfo.exceptions.InvalidTimezone: Invalid timezone "/usr/share/zoneinfo/Europe/Zurich"

The issue seems to be that `_get_unix_timezone` is unable to parse the string `'ZONE="/usr/share/zoneinfo/Europe/Zurich"\n` which is returned when the zonefile is read.

I think the issue is here that you expect there `Europe/Zurich`.

**Comment by austinbutler** [comment]
Same problem with an Ubuntu 18.04 container on Amazon Linux ECS-optimized. Worked around it for now by setting environment variable `TZ` to "UTC" in the container.

**Comment by sdispater** [comment]
It should be fixed in the latest release `2.0.1`

**Comment by Dmitrii-I** [comment]
thanks

**Comment by rkissos** [comment]
There is still an issue in 2.0.1:
```
  File "/opt/conda/envs/dev/lib/python3.6/site-packages/pendulum/tz/__init__.py", line 59, in local_timezone
    return get_local_timezone()
  File "/opt/conda/envs/dev/lib/python3.6/site-packages/pendulum/tz/local_timezone.py", line 30, in get_local_timezone
    tz = _get_system_timezone()
  File "/opt/conda/envs/dev/lib/python3.6/site-packages/pendulum/tz/local_timezone.py", line 58, in _get_system_timezone
    return _get_unix_timezone()
  File "/opt/conda/envs/dev/lib/python3.6/site-packages/pendulum/tz/local_timezone.py", line 222, in _get_unix_timezone
    return Timezone(tzpath)
  File "/opt/conda/envs/dev/lib/python3.6/site-packages/pendulum/tz/timezone.py", line 30, in __init__
    tz = read(name, extend=extended)
  File "/opt/conda/envs/dev/lib/python3.6/site-packages/pendulum/tz/zoneinfo/__init__.py", line 9, in read
    return Reader(extend=extend).read_for(name)
  File "/opt/conda/envs/dev/lib/python3.6/site-packages/pendulum/tz/zoneinfo/reader.py", line 50, in read_for
    raise InvalidTimezone(timezone)
pendulum.tz.zoneinfo.exceptions.InvalidTimezone: Invalid timezone "zoneinfo/UTC"
```

**Comment by Dmitrii-I** [comment]
@rkissos 

OK I am re-opening this issue. Could you help out and specify what Linux distribution you are using (e.g. `cat /etc/issue`).

**Comment by rkissos** [comment]
centos 7.4.1708 (Core)

**Comment by renstrom** [comment]
Same here (CentOS 7.4.1708). This issue is this part:

https://github.com/sdispater/pendulum/blob/10a76643c8f100a81368f3dba05dc74404ff9cdd/pendulum/tz/local_timezone.py#L219-L226

In the first iteration the variable `tzpath` has the value `'zoneinfo/UTC'`. This is wrong, and causes an error. Unfortunately you get a `InvalidTimezone` exception instead of one of the handled exceptions (i.e. `ValueError`, `IOError`, and `OSError`).

So you never get to `parts.pop(0)`, which would've removed the `'zoneinfo'` part from `parts`, and the next iteration would've been successful.

**Comment by sdispater** [comment]
This should be fixed in the latest release: `2.0.2`

**Comment by renstrom** [comment]
@sdispater are you thinking of https://github.com/sdispater/pendulum/commit/6ee68b9fdfb1bfd25db6c946d110cc4578a86958? Because I think you need to do a similar change to around [pendulum/tz/local_timezone.py#L224](https://github.com/sdispater/pendulum/blob/2.0.2/pendulum/tz/local_timezone.py#L224). At least that's where my bug/error happens.

**Comment by renstrom** [comment]
Some pdb debug output (v2.0.1).

```
(Pdb) l
215  	    tzpath = os.path.join(_root, 'etc/localtime')
216  	    if os.path.exists(tzpath) and os.path.islink(tzpath):
217  	        tzpath = os.path.realpath(tzpath)
218  	        parts = tzpath.split('/')[-2:]
219  	        import pdb; pdb.set_trace()
220  ->	        while parts:
221  	            tzpath = '/'.join(parts)
222  	            try:
223  	                return Timezone(tzpath)
224  	            except (ValueError, IOError, OSError):
225  	                pass
(Pdb) parts
['zoneinfo', 'UTC']
(Pdb) tzpath
'/usr/share/zoneinfo/UTC'
```

**Comment by sdispater** [comment]
@renstrom Yes, sorry about that. I didn't apply the fix to this case.

I will change it.

**Comment by lithammer** [comment]
>I will change it.

This is mostly a kind reminder in case you forgot. I could provide a PR in case you don't have time anytime soon.
